# fly.toml app configuration file generated for vanilla-node-backend-patient-lake-7225 on 2023-11-16T21:04:20-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vanilla-node-backend-patient-lake-7225"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
