# fly.toml app configuration file generated for vanilla-node-backend-cold-frog-2783 on 2023-11-16T20:40:40-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vanilla-node-backend-cold-frog-2783"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
